### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by Ayidana-Aboraah** [RestoneAGX/Bronze_Hermes#3]
- [x] Cleaner functions
- [x] Better Storage format (maybe CSV or custom file format)

**Comment by Phantom-Sync** [comment]
- [x] Use bound values properly, so we don't have to manually reload the values.
- [x] Windows Bug checks
- [x] File reorganization and reduction
- [x] Full Android Camera Debugging
- [x] Removing the hacky way we got the Sale struct to be a data item

**Comment by Ayidana-Aboraah** [comment]
We've done enough.
